### ISSUE TITLE
empty space before add to wishlist #116 

### ISSUE THREAD

**Issue by uuaqarahmed** [EsajeeSolutions/Esajeesite#22]
![image](https://cloud.githubusercontent.com/assets/527591/5998069/0d2b7928-aae5-11e4-81d8-e30b7d5f7e36.png)

**Comment by sabzesajee** [comment]
fixed

**Comment by kamrannaqvi** [comment]
Not fixed. the first problem is still there (extra space), now another problem is visible i.e. Add to Wishlist... links are now under the "Quick Overview" heading. 
(example: http://esajeecom.esajee.com/quickstart/index.php/perfumes-100ml-echo-men-davidoff.html)

**Comment by sabzesajee** [comment]
@uuaqarahmed  check plz

**Comment by sabzesajee** [comment]
@kamrannaqvi  please check now

**Comment by kamrannaqvi** [comment]
resolved.
