### ISSUE TITLE
Out of Stock items do not come In Stock when qty updated via SCM #139

### ISSUE THREAD

**Issue by kamrannaqvi** [EsajeeSolutions/Esajeesite#40]
![image](https://cloud.githubusercontent.com/assets/10416359/6408016/f0c7f90e-be6d-11e4-864f-843876d8aaa4.png)

**Comment by sabzesajee** [comment]
Fixed

**Comment by kamrannaqvi** [comment]
Can not be verified.
Stock adjustment feature not working at all. When I click [Save] after creating a new adjustment entry, nothing happens.

**Comment by kamrannaqvi** [comment]
Verified. 
An observation though; the items that come back in stock after adjustment, their prices still show 0.00 everywhere Magento/POS/SCM, i.e. the original prices are not recovered.
