### ISSUE TITLE
"Add. Info" & " Product Tags" tabs in item details page are empty #163

### ISSUE THREAD

**Issue by kamrannaqvi** [EsajeeSolutions/Esajeesite#63]
Many products show all info in the "Description" tab and the other 2 tabs "Add. Info" & " Product Tags" are empty. E.g. 076840100569, 041548018751.

http://esajeecom.esajee.com/quickstart/index.php/baby/baby-cereal/baby-cereal-200g-orange-milupa.html

http://esajeecom.esajee.com/quickstart/index.php/baby/baby-cereal/heinz-baby-cereal-dinners-golden-vegetables-125g.html

http://esajeecom.esajee.com/quickstart/index.php/baby/baby-food/gerber-baby-food-graduates-toddlers-pasta-stars-with-green-beans-155g.html

http://esajeecom.esajee.com/quickstart/index.php/bakery/cakes/no-wheat-g-free-wafer-100.html

http://esajeecom.esajee.com/quickstart/index.php/bakery/cakes/ameri-superroll-orang-85g.html

http://esajeecom.esajee.com/quickstart/index.php/bakery/bread/bread-whole-grain-500g-pema.html

http://esajeecom.esajee.com/quickstart/index.php/bakery/bread/mestemacher-bread-natural-three-grain-500g.html

http://esajeecom.esajee.com/quickstart/index.php/bakery/bread/ener-g-bread-free-brown-rice-loaf-540g.html

http://esajeecom.esajee.com/quickstart/index.php/bakery/bread/bread-c8-burritos-flour-tortillas-311g-oldelpaso.html

http://esajeecom.esajee.com/quickstart/index.php/bakery/bread/bread-naan-dawn.html

![166a](https://cloud.githubusercontent.com/assets/10416359/6552104/a6edf7d6-c663-11e4-9d7b-3f2d1a4ed5b2.png)
![166](https://cloud.githubusercontent.com/assets/10416359/6552105/a6efb63e-c663-11e4-85e8-e0c883db92d7.png)

**Comment by sabzesajee** [comment]
This is data entry issue. plz remove dev as mention in the screen shot from all the product having this issue
![info tab issuee](https://cloud.githubusercontent.com/assets/6996232/6554544/a46831be-c67e-11e4-9a21-ef8f2293578e.png)

**Comment by kamrannaqvi** [comment]
Please discuss this with Hussnain. Need to resolve via automated means.

**Comment by sabzesajee** [comment]
Done

**Comment by uuaqarahmed** [comment]
@sabzesajee this is partially fixed, see: http://esajeecom.esajee.com/quickstart/index.php/candy-and-chocolate/gum-and-mints/mentos-gum-spearmi-15-039-30g.html

**Comment by sabzesajee** [comment]
Fixed.

**Comment by kamrannaqvi** [comment]
verified.

**Comment by kamrannaqvi** [comment]
Problem still exist. 
http://esajeecom.esajee.com/quickstart/index.php/fruit-and-vegetable/fruit/polar-fruit-bottle-pears-slices-550g.html

**Comment by uuaqarahmed** [comment]
@kamrannaqvi please attach screenshot
